sudo: true                  # Required to install packages

services:
  - docker

language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

install:
  - composer self-update
  - composer up

script:
  - make test