#!/bin/bash

TEMPLATEENGINE_TEMPLATEFILE=$1
TEMPLATEENGINE_OUTPUTFILE=$2
TEMPLATEENGINE_PARAMS=$3
TEMPLATEENGINE_MIXIN=$4
workingdir=$(pwd)

docker run -v ${workingdir}:/config \
	-e "TEMPLATEENGINE_TEMPLATEFILE=${TEMPLATEENGINE_TEMPLATEFILE}" \
	-e "TEMPLATEENGINE_OUTPUTFILE=${TEMPLATEENGINE_OUTPUTFILE}" \
	-e "TEMPLATEENGINE_PARAMS=${TEMPLATEENGINE_PARAMS}" \
	-e "TEMPLATEENGINE_MIXIN=${TEMPLATEENGINE_MIXIN}" \
	-i philipw/yamltemplates